#!/bin/bash

CID=$1

[ -z "$CID" ] && CID=$(docker ps -lq)

if [[ ! "$CID" =~ "^[a-f0-9]{2,64}$" ]]; then
    NEW_ID=`docker ps -a | grep $CID | grep -v grep | awk -e '{print $1;}'`
    NUM_LINES=`echo $NEW_ID | wc -l`
    if [ -z "$NEW_ID" ]; then
        echo "no container like $CID"
        return 1
    fi
    if [ $NUM_LINES -ge 2 ]; then
        echo "$CID is ambiguous substring"
        return 1
    else
        CID=$NEW_ID
    fi
fi

docker logs -f $CID
