#!/bin/bash

CID=$1

[ -z "$CID" ] && CID=`hyper ps -ql`

[ `hyper ps -q | wc -l` -eq 1 ] && CID=`hyper ps -q`

if [[ ! "$CID" =~ "^[a-f0-9]{2,64}$" ]]; then
    NEW_ID=`hyper ps | grep $CID | grep -v grep | awk '{print $1;}'`
    NUM_LINES=`echo $NEW_ID | wc -l`
    if [ -z "$NEW_ID" ]; then
        echo "no container like $CID"
        return 1
    fi
    if [ $NUM_LINES -ge 2 ]; then
        echo "$CID is ambiguous substring"
        return 1
    else
        CID=$NEW_ID
    fi
fi
hyper exec -it $CID bash || hyper exec -it $CID sh
